default: &default
  adapter: mysql2
  # encoding: utf8mb4
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: question_app_development

test:
  <<: *default
  database: question_app_test

production:
  <<: *default
  database: question_app_production
  username: question_app
  password: <%= ENV["QUESTION_APP_DATABASE_PASSWORD"] %>
